using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Imageflow.CodeGen;

/// <summary>
/// Generates C# source files from V3 zennode schemas.
/// </summary>
public class V3Generator
{
    private readonly LoadedSchemas _schemas;

    public V3Generator(LoadedSchemas schemas) => _schemas = schemas;

    public List<(string Filename, string Content)> GenerateAll()
    {
        var files = new List<(string, string)>();

        // 1. Enums from node parameter schemas
        if (_schemas.NodeDefs is { Count: > 0 })
        {
            files.Add(("Enums.g.cs", GenerateEnums()));

            // 2. Per-node parameter classes
            foreach (var (nodeId, schema) in _schemas.NodeDefs)
            {
                var className = NodeIdToClassName(nodeId);
                files.Add(($"{className}.g.cs", GenerateNodeClass(nodeId, className, schema)));
            }
        }

        // 3. Querystring builder
        if (_schemas.QsKeyGroups is { Count: > 0 })
        {
            files.Add(("ZenQuerystring.g.cs", GenerateQuerystringBuilder()));
        }

        return files;
    }

    // ─── Naming helpers ───

    static string NodeIdToClassName(string nodeId) =>
        string.Join("", nodeId.Split('.').Select(PascalCase));

    static string PascalCase(string s) =>
        string.Join("", s.Split('_').Select(part =>
            part.Length == 0 ? "" : char.ToUpperInvariant(part[0]) + part[1..]));

    static string CSharpType(JsonObject schema, bool optional)
    {
        var typeVal = schema["type"];
        var typeStr = typeVal switch
        {
            JsonValue v when v.GetValueKind() == JsonValueKind.String => v.GetValue<string>(),
            JsonArray arr => arr.Select(x => x?.GetValue<string>()).FirstOrDefault(t => t != "null") ?? "string",
            _ => "string"
        };

        var baseType = typeStr switch
        {
            "number" => "float",
            "integer" => schema["minimum"]?.GetValue<long>() >= 0 ? "uint" : "int",
            "boolean" => "bool",
            "string" => "string",
            "array" => "float[]",
            _ => "string"
        };

        return optional && baseType is not ("string" or "float[]") ? $"{baseType}?" : baseType;
    }

    static string? CSharpDefault(JsonObject schema, string csType)
    {
        var def = schema["default"];
        if (def is null) return null;
        return csType switch
        {
            "float" or "float?" => $"{def.GetValue<double>()}f",
            "int" or "int?" => def.GetValue<long>().ToString(),
            "uint" or "uint?" => def.GetValue<long>().ToString(),
            "bool" or "bool?" => def.GetValue<bool>() ? "true" : "false",
            "string" => $"\"{def.GetValue<string>()}\"",
            _ => null
        };
    }

    // ─── Enum generation ───

    string GenerateEnums()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated from zennode schemas. Do not edit.");
        sb.AppendLine("namespace Imageflow.Fluent.V3;");
        sb.AppendLine();

        var seen = new HashSet<string>();

        foreach (var (_, schema) in _schemas.NodeDefs!)
        {
            if (schema["properties"] is not JsonObject props) continue;
            foreach (var (paramName, paramSchema) in props)
            {
                if (paramSchema is not JsonObject ps) continue;
                if (ps["enum"] is not JsonArray variants) continue;

                var enumName = PascalCase(paramName);
                if (!seen.Add(enumName)) continue;

                var title = ps["title"]?.GetValue<string>() ?? ps["description"]?.GetValue<string>();
                if (title != null)
                {
                    sb.AppendLine($"/// <summary>{EscapeXml(title)}</summary>");
                }

                sb.AppendLine($"public enum {enumName}");
                sb.AppendLine("{");

                var labels = ps["x-zennode-enum-labels"]?.AsArray();
                var i = 0;
                foreach (var variant in variants)
                {
                    var name = variant?.GetValue<string>() ?? "Unknown";
                    var csName = PascalCase(name);
                    if (labels?[i] is JsonObject label && label["description"]?.GetValue<string>() is { Length: > 0 } desc)
                    {
                        sb.AppendLine($"    /// <summary>{EscapeXml(desc)}</summary>");
                    }
                    sb.AppendLine($"    {csName},");
                    i++;
                }

                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    // ─── Node class generation ───

    string GenerateNodeClass(string nodeId, string className, JsonObject schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated from zennode schema: {nodeId}");
        sb.AppendLine("using System.Text.Json.Nodes;");
        sb.AppendLine("namespace Imageflow.Fluent.V3;");
        sb.AppendLine();

        var desc = schema["description"]?.GetValue<string>();
        if (desc != null)
        {
            sb.AppendLine($"/// <summary>{EscapeXml(desc)}</summary>");
        }

        var role = schema["x-zennode-role"]?.GetValue<string>() ?? "";
        sb.AppendLine($"public sealed partial class {className}");
        sb.AppendLine("{");

        var props = schema["properties"]?.AsObject();
        if (props == null)
        {
            sb.AppendLine("}");
            return sb.ToString();
        }

        // Properties
        foreach (var (paramName, paramSchema) in props)
        {
            if (paramSchema is not JsonObject ps) continue;
            var isOptional = ps["x-zennode-optional"]?.GetValue<bool>() == true;
            var csType = CSharpType(ps, isOptional);
            var csName = PascalCase(paramName);
            var defaultVal = CSharpDefault(ps, csType);

            var title = ps["title"]?.GetValue<string>();
            if (title != null) sb.AppendLine($"    /// <summary>{EscapeXml(title)}</summary>");

            var unit = ps["x-zennode-unit"]?.GetValue<string>();
            if (unit is { Length: > 0 }) sb.AppendLine($"    /// <remarks>Unit: {unit}</remarks>");

            sb.Append($"    public {csType} {csName} {{ get; set; }}");
            if (defaultVal != null) sb.Append($" = {defaultVal};");
            sb.AppendLine();
            sb.AppendLine();
        }

        // Fluent setters
        foreach (var (paramName, paramSchema) in props)
        {
            if (paramSchema is not JsonObject ps) continue;
            var isOptional = ps["x-zennode-optional"]?.GetValue<bool>() == true;
            var csType = CSharpType(ps, isOptional);
            var csName = PascalCase(paramName);
            sb.AppendLine($"    public {className} Set{csName}({csType} value) {{ {csName} = value; return this; }}");
        }

        sb.AppendLine();

        // ToJsonNode()
        sb.AppendLine("    internal JsonNode ToJsonNode()");
        sb.AppendLine("    {");
        sb.AppendLine("        var obj = new JsonObject();");
        foreach (var (paramName, paramSchema) in props)
        {
            if (paramSchema is not JsonObject ps) continue;
            var isOptional = ps["x-zennode-optional"]?.GetValue<bool>() == true;
            var csType = CSharpType(ps, isOptional);
            var csName = PascalCase(paramName);

            if (isOptional || csType.EndsWith('?'))
                sb.AppendLine($"        if ({csName} != null) obj.Add(\"{paramName}\", JsonValue.Create({csName}));");
            else if (csType == "string")
                sb.AppendLine($"        if (!string.IsNullOrEmpty({csName})) obj.Add(\"{paramName}\", {csName});");
            else
                sb.AppendLine($"        obj.Add(\"{paramName}\", JsonValue.Create({csName}));");
        }
        sb.AppendLine("        return obj;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ─── Querystring builder ───

    string GenerateQuerystringBuilder()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated from zennode RIAPI key registry.");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("namespace Imageflow.Fluent.V3;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Fluent builder for RIAPI querystrings with compile-time key validation.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed partial class ZenQuerystring");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly Dictionary<string, string> _params = new();");
        sb.AppendLine();

        foreach (var (nodeId, nodeInfo) in _schemas.QsKeyGroups!)
        {
            if (nodeInfo["keys"] is not JsonArray keys) continue;
            foreach (var keyInfo in keys)
            {
                if (keyInfo is not JsonObject ki) continue;
                var key = ki["key"]?.GetValue<string>();
                if (key == null) continue;

                var label = ki["label"]?.GetValue<string>() ?? key;
                var desc = ki["description"]?.GetValue<string>();
                var valueSchema = ki["value_schema"]?.AsObject();
                var paramType = valueSchema?["type"]?.GetValue<string>() switch
                {
                    "number" => "float",
                    "integer" => "int",
                    "boolean" => "bool",
                    _ => "string"
                };

                var methodName = KeyToMethodName(key);

                sb.AppendLine($"    /// <summary>{EscapeXml(label)}</summary>");
                if (desc is { Length: > 0 })
                    sb.AppendLine($"    /// <remarks>{EscapeXml(desc)}</remarks>");

                sb.AppendLine($"    public ZenQuerystring {methodName}({paramType} value)");
                sb.AppendLine("    {");
                if (paramType == "bool")
                    sb.AppendLine($"        _params[\"{key}\"] = value ? \"true\" : \"false\";");
                else
                    sb.AppendLine($"        _params[\"{key}\"] = value.ToString();");
                sb.AppendLine("        return this;");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        // Build method
        sb.AppendLine("    /// <summary>Build the querystring (without leading ?).</summary>");
        sb.AppendLine("    public string Build()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_params.Count == 0) return \"\";");
        sb.AppendLine("        var sb = new StringBuilder();");
        sb.AppendLine("        var first = true;");
        sb.AppendLine("        foreach (var (k, v) in _params)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!first) sb.Append('&');");
        sb.AppendLine("            sb.Append(Uri.EscapeDataString(k));");
        sb.AppendLine("            sb.Append('=');");
        sb.AppendLine("            sb.Append(Uri.EscapeDataString(v));");
        sb.AppendLine("            first = false;");
        sb.AppendLine("        }");
        sb.AppendLine("        return sb.ToString();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public override string ToString() => Build();");
        sb.AppendLine("}");

        return sb.ToString();
    }

    static string KeyToMethodName(string key) =>
        string.Join("", key.Split('.', '_').Select(PascalCase));

    static string EscapeXml(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
